name: CICD

on: push
jobs:
 build_job: 
   runs-on: ubuntu-latest
   steps:
   - name: Run many tests
     run: echo "build job"
    
    
 test_job:
   needs: build_job 
   runs-on: ubuntu-latest
   steps:
   - name: Deploy
     run: echo "test job"
      
 deploy_job:
   needs: test_job 
   runs-on: ubuntu-latest
   steps:
   - name: echo "deploy job"
     run: echo "deploy job"   